# Generated by Django 5.2.10 on 2026-01-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station_namber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('namber_1', models.IntegerField()),
                ('namber_2', models.IntegerField()),
                ('namber_3', models.IntegerField()),
                ('namber_4', models.IntegerField()),
                ('namber_5', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
