# Generated by Django 5.2.10 on 2026-02-03 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_station_namber_delete_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uchastok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='значение_по_умолчанию', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='station_namber',
            name='uchastoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='station.uchastok'),
            preserve_default=False,
        ),
    ]
